/**
 * Deploy-time Supabase browser config (publishable key only — safe in the browser).
 * Generated by scripts/inject-supabase-env.cjs during Netlify build.
 * Do not edit by hand; set Netlify env vars instead.
 */
(function () {
  if (typeof window === 'undefined') return;
  window.__SUPABASE_CONFIG__ = Object.assign({}, window.__SUPABASE_CONFIG__ || {}, {
    url: "****************e.co",
    anonKey: "sb_publishable_j_1EFLBa4bFxClGLGKo6JQ_hoq4OqG4",
  });
})();
